import type { Metadata } from 'next'
import { PT_Sans,Nunito} from 'next/font/google' 
import './globals.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false


const ptSans = PT_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
})


const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '700'], // You can adjust the weights as needed
  style: ['normal', 'italic'],
})




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={ptSans.className}>{children}</body>
    </html>
  )
}
